### ISSUE TITLE
Bug: Delegation via Keplr with Ledger

### ISSUE THREAD

**Issue by keupsonite** [BitCannaGlobal/web-wallet#4]
I get an error, impossible to delegate using Keplr with Ledger:

"Staking failed: Error: Data is invalid : Unexpected characters."

![2021-10-14_18h44_36](https://user-images.githubusercontent.com/2184898/137362064-4b676b85-bfd3-40d9-9dd7-8327cc97aaf6.gif)

**Comment by atmoner** [comment]
> I assure you that my gif is whole, you must have a loading problem. I don't have the possibility to redo the transaction, I don't have enough BCNA, because I have delegated by CLI, the interface prevents me, sorry.

No problem, I reproduced the error locally, I will work on it! thank you

**Comment by zlounes** [comment]
I deleted my old message, I was wrong. I will take a look at it, but I have no idea if it is possible. If I clone the repository I will be able to simulate locally with a testnet for example? If yes, would you have a configuration to give me?

**Comment by zlounes** [comment]
Replacing getOfflineSigner by getOfflineSignerAuto make Keplr with Ledger works!
