### ISSUE TITLE
[Bug] - Crash without address

### ISSUE THREAD

**Issue by DDeAlmeida** [BitCannaGlobal/web-wallet#5]
1 - Go to https://wallet.bitcanna.io/welcome
2 - Click on "Continue without address"
3 - Click on your super best mega nice validator "PandaTeam" ^^or go to https://wallet.bitcanna.io/validators/bcnavaloper1a5498yallpyr2zgedsj03v75nswe88h3xhajz4
4 - Crash :
![image](https://user-images.githubusercontent.com/52310650/141430432-fbf5f04e-3d1f-4184-853a-830d5b3b2284.png)

**Comment by atmoner** [comment]
Hello @DDeAlmeida 
Indeed, there was a problem with the session, I fixed the problem (https://github.com/BitCannaGlobal/web-wallet/commit/185731b33e9d7abc84851a62ade81413005b46c2) and put into production, the problem is solved!

Thank you for letting us know :+1:
